### ISSUE TITLE
predictive search box to the top of every page/home page

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#15]
As requested:  Add a predictive search box to the top of every page.  This search box needs to handle database names with spaces or no spaces, apostrophes, and you should be able to type in any part of the database title (ie. AccessPharmacy or Access Pharmacy; Hoover’s or Cabell’s; “Media” would bring up MRI MediaMark). In other words, it needs be a forgiving search.

**Comment by MichaelRBond** [comment]
I'm a little concerned that with the A to Z letter list on the top of ever page AND the database search on the top of every page we will be crowding it too much. 

Shouldn't the search just be a part of the library search, which is a part of every page, and not part of the database app itself? 

I think the bigger issue here is that the search box was omitted from the template.  Which should be upgraded to include predictive search for database titles. 

@jetapia @timbroadwater

**Comment by MichaelRBond** [comment]
The predictive search box is on the index page.

**Comment by timbroadwater** [comment]
Yes, this diesn't work for me for some reason. Also, the A-Z will only be on the homepage and the title pages.

**Comment by MichaelRBond** [comment]
Search box has been moved out to an include file. It wasn't working properly on the index page because it was being rendered twice (and hidden once). Removed the first (hidden) rendering on the homepage. 

works in both the tab bar and the homepage for me now.

**Comment by timbroadwater** [comment]
#49
