### ISSUE TITLE
Highlight new and trial databases

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#18]

**Comment by MichaelRBond** [comment]
I've added the code for it. needs icons and styled.

**Comment by MichaelRBond** [comment]
Need a feature section on homepage similar to : http://libguides.wvu.edu/az.php

**Comment by MichaelRBond** [comment]
@timbroadwater on the example page (linked above) all they do is display the same database listing, in a smaller div. So, i've done the same thing fo rthe sake of this. 

we may just want to hide the accordion stuff when in the new/trial div.

**Comment by timbroadwater** [comment]
This is now accessible on the homepage, and is in the coding you need to do for  Color Facets #34 .

**Comment by MichaelRBond** [comment]
They specifically asked for the extra box to be added, with the details of the databases. The highlight box listed all the New and Trial databases immediately. 

I don't think we need the highlight box on internal pages, but on the app homepage I think we are going to need it. 

This code will add it back in. 
`{local var="highlighted_databases"}`

Was removed in: d58fd329

**Comment by timbroadwater** [comment]
I know what they specifically asked for, but I'm not going to add it because it interferes with the homepage dynamic. This is one click, so this is an enhancement, not an error.

**Comment by MichaelRBond** [comment]
This is a two part issue. 

1) is the box
2) are the icons in the database listing. 

#1 can wait to see if it is still necessary.
#2 is needed for this version.

**Comment by MichaelRBond** [comment]
#2 is being covered by this issue, i think: https://github.com/wvulibraries/databases/issues/34

**Comment by MichaelRBond** [comment]
This issue has been split up into 

https://github.com/wvulibraries/databases/issues/57
and
https://github.com/wvulibraries/databases/issues/58

closing this issue to work from the separated issues.
