### ISSUE TITLE
Report a Resource Error

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#19]
As requested: Add a “Report a Resource Error” link to a form like this: http://library.pdx.edu/research/eresource-report/

**Comment by MichaelRBond** [comment]
Page is created. Needs linked and styled:

Report page:
http://localhost:8050/databases/report/

Thank you page:
http://localhost:8050/databases/report/thanks/

Error Page:
http://localhost:8050/databases/report/error/

@jetapia Please develop extra the content for the thanks and error pages (You won't be able to see them at the links above unless you download the repo and do a vagrant up. You can browse to them in github though).

**Comment by jmm0177** [comment]
Mike—You’re going to have to show me how to set this up.

Jessica

**Comment by timbroadwater** [comment]
Done
