### ISSUE TITLE
Facet improvements

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#26]
These are from the usability testing. How do these get incorporated now that facets by resource type have been removed? 
1. Facets should only populate under resource types dynamically as they
   are applicable and remain to what’s pre and post breadcrumb faceting
2. Possibly develop facets to work in reverse order, so by resource type
   then by subject.

**Comment by timbroadwater** [comment]
Create visual understanding with color for facets in the left-hand, and color code (and possibly use different icons) for tags based on resource type versus subject

**Comment by timbroadwater** [comment]
THis is moot now
