### ISSUE TITLE
Breadcrumbs for Subject, Subject <, Title, and Title <

### ISSUE THREAD

**Issue by timbroadwater** [wvulibraries/databases_deprecated#33]
Add ‘by Subject’ as a facet

**Comment by timbroadwater** [comment]
![screen shot 02-22-16 at 02 53 pm](https://cloud.githubusercontent.com/assets/6225634/13230688/5c77f178-d974-11e5-8977-ed09e04e806b.png)

**Comment by timbroadwater** [comment]
![screen shot 02-22-16 at 02 56 pm](https://cloud.githubusercontent.com/assets/6225634/13230743/8bd3822a-d974-11e5-963e-2f6ac93b6fd5.png)

**Comment by MichaelRBond** [comment]
A to Z and subjects are done.

**Comment by timbroadwater** [comment]
Awesome!
