### ISSUE TITLE
Color Facets

### ISSUE THREAD

**Issue by timbroadwater** [wvulibraries/databases_deprecated#34]
Create visual understanding with color for facets in the left-hand, and color code (and possibly use different icons) for tags based on resource type versus subject

**Comment by timbroadwater** [comment]
@MichaelRBond is there an icon, class, or something that I can do to add customization for ALumni, New, and Trail databases?

**Comment by MichaelRBond** [comment]
In class_lists.php, in the "databases" method, find the lines:
// Print if a new database
// print if a trial database

the trial and new can be styled there. 

Alumni doesn't need high lighted.

**Comment by timbroadwater** [comment]
Why doesn't Alumni need highlighted?

**Comment by MichaelRBond** [comment]
It only needs to be available from the home page. Its a matter of finding "which ones" are alumni accessible databases, not highlighting them while browsing.
