### ISSUE TITLE
Additive facets aren't working

### ISSUE THREAD

**Issue by timbroadwater** [wvulibraries/databases_deprecated#6]
When I click on articles, and then add bibliographies, it doesn't further reduce, but rather just loads bibliographies.

**Comment by MichaelRBond** [comment]
Correct. Articles is a resource type. Bibliographies is a subject. 

I asked you about that behavior yesterday. You said to take them to the subject page instead of Faceting further when clicking on the tags.

**Comment by timbroadwater** [comment]
I'm referring to the faceted bread crumbs.
