### ISSUE TITLE
Move search box to same place on all pages

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#61]
Title Search Box – should be located in the same spot on every page.  Top left as on the first page seems best.  It is much more evident there.

**Comment by MichaelRBond** [comment]
Should we? Seems like it should be more prominent on the front page.

**Comment by timbroadwater** [comment]
This stays as is, but you have to fix the one on the homepage so the hidden one doesn't mess up the search box.
