### ISSUE TITLE
delete issue

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/databases_deprecated#72]
The problem of duplicate titles persists. In development is Digital National Security Archives, first entered in 2012 as a trial. Jan started a new trial but accidently entered the title as National Digital Security Archives. I'm not able to make corrections to the title. I get a duplicate title error. Nor am I able to delete the old one. It says the deletion went through, but it is never deleted. Please help. The new trial is now displaying with the wrong title. 

Out of order sign placed:
 Sign placed
Comments:   Mike Bond: 2016-03-12 3:06:25pm
I didn't know that we needed to allow duplicate titles. 

I opened up duplicate URLs in the newest release. 

I'll try take a look this weekend.
Penny Pugh: 2016-03-13 1:34:38pm
Maybe we don't need duplicate titles, though some show up when an old trial is duplicated rather than edited. But My problem is that I can neither edit the new entry - which has the wrong title - or delete the old trial. I'm not sure why I can't delete.
Mike Bond: 2016-03-14 7:33:31am
The delete error seems to be an issue with the framework, because delete works fine on my development server. 

I'll need to see why the versions are different and do some testing before updating the framework (its used for multiple web applications). 

Mike Bond: 2016-03-14 7:35:07am
In the mean time, i would suggest the "work around" be to edit the original entry with the updated information, and then switch the new one to development. 

Editing the original entry would be the preferred way to handle "new" databases that already have a previous entry.
Penny Pugh: 2016-03-14 10:54:01am
I edited the old entry and put the new one in development. Tried once again to delete it. I get a form successful message, but it is not deleted.
Mike Bond: 2016-03-14 10:56:22am
Yeah. We'll get the delete fixed (its not a bug in the database app. its a bug in the software the database app uses. I have it fixed in development already, i just need to make sure the fix isn't going to break anything else we have in production). 

Thanks

**Comment by jmm0177** [comment]
It appears that the delete is still not working.  Now that we're cancelling a bunch of stuff, can someone take a look at this?

**Comment by MichaelRBond** [comment]
Looking into what the fix was.

**Comment by MichaelRBond** [comment]
This was fixed with updates to EngineAPI-Modules.
